MvcCoreLinqToSQL2/Models/Empleado.cs
namespace MvcCoreLinqToSQL.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcCoreLinqToSQL2/Models/Enfermo.cs
namespace MvcCoreLinqToSQL2.Models
{
    public class Enfermo
    {
        public string Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
    }
}

MvcCoreLinqToSQL2/Models/ErrorViewModel.cs
namespace MvcCoreLinqToSQL2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreLinqToSQL2/Models/ResumenEmpleados.cs
using MvcCoreLinqToSQL.Models;

namespace MvcCoreLinqToSQL2.Models
{
    public class ResumenEmpleados
    {
        public int Personas { get; set; }
        public int MaximoSalario { get; set; }
        public double MediaSalarial { get; set; }
        public List<Empleado> Empleados { get; set; }
    }
}

MvcCoreLinqToSQL2/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL.Models;
using MvcCoreLinqToSQL.Repositories;
using MvcCoreLinqToSQL2.Models;

namespace MvcCoreLinqToSQL.Controllers
{
    public class EmpleadosController : Controller
    {
        RepositoryEmpleados repo;

        public EmpleadosController()
        {
            this.repo = new RepositoryEmpleados();
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int idempleado)
        {
            Empleado empleado = this.repo.FindEmpleado(idempleado);
            return View(empleado);
        }

        public IActionResult BuscadorEmpleados()
        {
            return View();
        }
        [HttpPost]
        public IActionResult BuscadorEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = this.repo.GetEmpleadosOficioSalario(oficio, salario);
            return View(empleados);
        }

        public IActionResult EmpleadosOficio()
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            return View();
        }
        [HttpPost]
        public IActionResult EmpleadosOficio(string oficio)
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            ResumenEmpleados resumen = this.repo.GetEmpleadosOficio(oficio);
            return View(resumen);
        }
    }
}

MvcCoreLinqToSQL2/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL2.Models;
using MvcCoreLinqToSQL2.Repositories;

public class EnfermosController : Controller
{
    private RepositoryEnfermos repo;

    public EnfermosController()
    {
        this.repo = new RepositoryEnfermos();
    }

    public IActionResult Index()
    {
        List<Enfermo> enfermos = this.repo.GetEnfermos();
        return View(enfermos);
    }

    public IActionResult Details(string inscripcion)
    {
        Enfermo enfermo = this.repo.FindEnfermo(inscripcion);
        return View(enfermo);
    }

    public IActionResult Delete(string inscripcion)
    {
        this.repo.DeleteEnfermo(inscripcion);
        return RedirectToAction("Index");
    }
}

MvcCoreLinqToSQL2/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL2.Models;

namespace MvcCoreLinqToSQL2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreLinqToSQL2/Views/Empleados/Details.cshtml
@model Empleado

<h1>Details</h1>

<p>
    <a asp-controller="Empleados" asp-action="Index">Back to list</a>
</p>

<ul class="list-group">
    <li class="list-group-item">@Model.Apellido</li>
    <li class="list-group-item">@Model.Oficio</li>
    <li class="list-group-item">@Model.Salario</li>
    <li class="list-group-item">@Model.IdDepartamento</li>
</ul>

MvcCoreLinqToSQL2/Views/Empleados/EmpleadosOficio.cshtml
@model ResumenEmpleados

@{
	List<string> oficios =
		ViewData["Oficios"] as List<string>;
}

<h1>LAMBDA EXPRESSION LINQ</h1>

<form method="post">
	<label>Oficio: </label>
	<select name="oficio" class="form-control">
		@foreach (string oficio in oficios)
		{
			<option value="@oficio">@oficio</option>
		}
	</select>
	<button class="btn btn-info">
		Buscar Empleados
	</button>
</form>

@if (Model != null)
{
	<ul class="list-group">
		<li class="list-group-item">
			Personas: @Model.Personas
		</li>
		<li class="list-group-item">
			Máximo salario: @Model.MaximoSalario
		</li>
		<li class="list-group-item">
			Media salarial: @Model.MediaSalarial
		</li>
	</ul>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Apellido</th>
				<th>Oficio</th>
				<th>Salario</th>
			</tr>
		</thead>
		<tbody>
			@foreach (Empleado empleado in Model.Empleados)
			{
				<tr>
					<td>@empleado.Apellido</td>
					<td>@empleado.Oficio</td>
					<td>@empleado.Salario</td>
				</tr>
			}
		</tbody>
	</table>
}

MvcCoreLinqToSQL2/Views/Empleados/Index.cshtml
@model List<Empleado>

<h1>Linq Empleados</h1>
<table>
	<thead>
		<tr>
			<th>Apellido</th>
			<th>Oficio</th>
			<th>Salario</th>
		</tr>
	</thead>
	<tbody>
		@foreach (Empleado empleado in Model)
		{
			<tr>
				<td>@empleado.Apellido</td>
				<td>@empleado.Oficio</td>
				<td>@empleado.Salario</td>
				<td>
					<a asp-controller="Empleados" asp-action="Details" asp-route-idempleado="@empleado.IdEmpleado">Details</a>
				</td>
			</tr>
		}
	</tbody>
</table>

MvcCoreLinqToSQL2/Views/Enfermos/Details.cshtml
@model Enfermo

<h1 style="color:blue">Details</h1>

<p>
    <a asp-controller="Enfermos"
       asp-action="Index">Back to list</a>
</p>

<ul class="list-group">
    <li class="list-group-item list-group-item-primary">
        Apellido: @Model.Apellido
    </li>
    <li class="list-group-item list-group-item-danger">
        Inscripción: @Model.Inscripcion
    </li>
    <li class="list-group-item list-group-item-info">
        Fecha nacimiento: @Model.FechaNacimiento.ToLongDateString()
    </li>
    <li class="list-group-item list-group-item-success">
        Dirección: @Model.Direccion
    </li>
</ul>

MvcCoreLinqToSQL2/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<h1>Enfermos Linq To Sql</h1>

<ul class="list-group">
    @foreach (Enfermo enfermo in Model)
    {
        <li class="list-group-item">
            @enfermo.Apellido
            <a asp-controller="Enfermos"
               asp-action="Details"
               asp-route-inscripcion="@enfermo.Inscripcion"
               class="btn btn-dark">
                Details
            </a>
            <a asp-controller="Enfermos"
               asp-action="Delete"
               asp-route-inscripcion="@enfermo.Inscripcion"
               class="btn btn-danger">
                Delete
            </a>
        </li>
    }
</ul>

MvcCoreLinqToSQL2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreLinqToSQL</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreLinqToSQL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreLinqToSQL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="EmpleadosOficio">Lambda Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcCoreLinqToSQL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>